### ISSUE TITLE
Logout button is broken

### ISSUE THREAD

**Issue by mbarton** [rcpch/rcpch-audit-engine#837]
1) Log in
2) Click log out

*Expected*

You're logged out!

*Actual*

You're not! It shows a blank white page.

You can see a 405 in the dev tools:

![Screenshot from 2024-03-11 10-54-10](https://github.com/rcpch/rcpch-audit-engine/assets/395805/a4102aff-84d6-4aee-a5c0-0513fcc42afb)

This is because we automatically upgraded to a newer version of Django which removed logging out from a GET request as a security measure: https://docs.djangoproject.com/en/5.0/releases/4.1/#log-out-via-get

**Comment by eatyourpeas** [comment]
I thought I fixed this?

**Comment by mbarton** [comment]
Hmm it's still broken for me on `development` today. I saw you commented about it here https://github.com/rcpch/rcpch-audit-engine/pull/828#pullrequestreview-1923476181, maybe it's on a branch somewhere?

**Comment by eatyourpeas** [comment]
I think this happened just before @pacharanero force pushed something so it is possible that change got lost/overwritten.
I think the easiest thing is if I create a branch off development now using this issue and fix and send you a PR?
